apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: proj-no-secrets
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5000
  type: NodePort
