apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: proj-no-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: gsaiadhinathareddy/patients-app:v1
        env:
        - name: DB_HOST
          value: mysqldb-service
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: adhi
        - name: DB_PASSWORD
          value: adhi@123
        - name: DB_NAME
          value: patientsdb
        ports:
        - containerPort: 3000
