apiVersion: v1
kind: PersistentVolume
metadata:
  name: patients-pv
  namespace: proj-no-secrets
spec:
  storageClassName: patients-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: /data/patients-pv/
