apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patients-pvc
  namespace: proj-no-secrets
spec:
  storageClassName: patients-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Specify the size you need
