apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: proj1
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer