apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: proj1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: ckr123/nodeapp-mysql:v1
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: proj1-configmap
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: proj1-configmap
              key: db_port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        ports:
        - containerPort: 5000
